### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bianconim** [sfarrens/sfof#17]
**Describe the bug**
I was testing the SFOF code using docker on a local server. The run (using the phot_test example) appers to reach completion, but there's no file output despite the message attached in the Screenshots section

**To Reproduce**
docker run -v {$PATHTOWORKDIR}:/workdir -it sfarrens/sfof /bin/bash -c "cd workdir && sfof"

**Expected behaviour**
The code should output two "*.dat" files

**Screenshots**
Merging 2151 candidates.
Total clusters detected with Ngal >= 3: 674
Cluster properties being written to: test_phot.dat_clusters_0.86_1_phot.dat
Cluster member properties being written to: test_phot.dat_members_0.86_1_phot.dat
 Time Elapsed: [0 days | 0 h | 0 m | 0 s]

**Desktop (please complete the following information):**
Linux  4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

**Comment by sfarrens** [comment]
Hi @bianconim 

I have just run the following test on my own computer (macOS 10.15.7):

```bash
cd sfof/examples/phot_test
docker run -v ${PWD}:/workdir -it sfarrens/sfof /bin/bash -c "cd workdir && sfof"
```

and I get both `test_phot.dat_members_0.86_1_phot.dat` and `test_phot.dat_clusters_0.86_1_phot.dat` files.

I think there is a small typo in your command. I assume `{$PATHTOWORKDIR}` should be `${PATHTOWORKDIR}` if this is an actual environment variable you defined. The standard `${PWD}` variable should work on most UNIX systems without having to define anything. 

I doubt this is the source of the problem as `sfof` should not run if it cannot find a parameter file. I will try to test the docker image on a system closer to yours to see if I can reproduce this bug. In the meantime the only thing I can suggest is to copy and paste my execution command exactly to see if you encounter the same problem.

**Comment by bianconim** [comment]
Apologies, that was a typo in my comment indeed. As you have suggested, I have used your command but this doesn't solve the problem. Thank you for your help.

**Comment by bianconim** [comment]
I have tracked the problem down to permission to write on the mounted folder on the cluster were was using Docker. I have stated using Singularity instead and solved the issue.

Thanks!

**Comment by sfarrens** [comment]
Ah, good news!

**Comment by sfarrens** [comment]
Shall I close this issue then?

**Comment by bianconim** [comment]
I'll close it now, thank you.
